# Atividade 1 — Exercícios com os comandos básicos de pandas para EDA


Responda as perguntas abaixo no notebook (cada resposta deve ter ao menos uma célula de código que produza o output e, logo abaixo, uma célula de texto com a sua interpretação).

## 1) Carregue o dataset e mostre as primeiras 10 linhas.

In [1]:
import pandas as pd
data = pd.read_csv("/content/emendas.csv")

In [2]:
data.head(10)

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
0,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,ALVORADA - RS,4300604,ALVORADA,4300000.0,...,1D73,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0.0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,"700000,00","0,00","0,00","0,00","690900,00","9100,00"
1,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SANTA ISABEL DO PARÁ - PA,1506500,SANTA ISABEL DO PARÁ,1500000.0,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0.0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"487500,00","0,00","0,00","0,00","487500,00","0,00"
2,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,BARRA BONITA - SC,4202099,BARRA BONITA,4200000.0,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0.0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"100000,00","0,00","0,00","0,00","0,00","100000,00"
3,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,ARARAQUARA - SP,3503208,ARARAQUARA,3500000.0,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0.0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"243750,00","0,00","0,00","0,00","243750,00","0,00"
4,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CAMPO LARGO - PR,4104204,CAMPO LARGO,4100000.0,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0.0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"1658333,94","0,00","0,00","0,00","527200,00","1131133,94"
5,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CAMPINAS DO SUL - RS,4303806,CAMPINAS DO SUL,4300000.0,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0.0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"243750,00","0,00","0,00","0,00","0,00","243750,00"
6,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,MORENO - PE,2609402,MORENO,2600000.0,...,20RP,APOIO A INFRAESTRUTURA PARA A EDUCACAO BASICA,0.0,INFRAESTRUTURA PARA A EDUCACAO BASICA - DESPES...,"700000,00","0,00","0,00","0,00","700000,00","0,00"
7,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,NOVA FLORESTA - PB,2510105,NOVA FLORESTA,2500000.0,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0.0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"278700,00","0,00","0,00","0,00","0,00","278700,00"
8,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SANTIAGO DO SUL - SC,4215695,SANTIAGO DO SUL,4200000.0,...,20ZV,FOMENTO AO SETOR AGROPECUARIO,0.0,FOMENTO AO SETOR AGROPECUARIO - DESPESAS DIVERSAS,"300000,00","300000,00","300000,00","0,00","0,00","0,00"
9,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CIANORTE - PR,4105508,CIANORTE,4100000.0,...,1D73,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0.0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,"245850,00","0,00","0,00","0,00","0,00","245850,00"

Explique em uma frase o que você observa nas primeiras 10 linhas.

In [ ]:
# é visualizado nas 10 primeiras linhas emendas individuais para determinados municípios, também demonstrando alguns nomes, a ação a ser efetuada e os valores. também é notado a falta de informações em alguns setores

## 2) Quantas linhas e colunas o dataset possui?

In [4]:
data.shape

(6606, 28)

Explique o que esses números significam.

In [ ]:
#o código possui 6606 linhas e 28 colunas

## 3) Liste os nomes das colunas e descreva brevemente o que você entende que cada coluna representa.

In [6]:
data.dtypes

Código da Emenda                       object
Ano da Emenda                           int64
Tipo de Emenda                         object
Código do Autor da Emenda              object
Nome do Autor da Emenda                object
Número da emenda                       object
Localidade de aplicação do recurso     object
Código Município IBGE                  object
Município                              object
Código UF IBGE                        float64
UF                                     object
Região                                 object
Código Função                         float64
Nome Função                            object
Código Subfunção                      float64
Nome Subfunção                         object
Código Programa                       float64
Nome Programa                          object
Código Ação                            object
Nome Ação                              object
Código Plano Orçamentário             float64
Nome Plano Orçamentário                object
Valor Empenhado                        object
Valor Liquidado                        object
Valor Pago                             object
Valor Restos A Pagar Inscritos         object
Valor Restos A Pagar Cancelados        object
Valor Restos A Pagar Pagos             object
dtype: object

Escreva sua breve descrição das colunas, como se estivesse criando um dicionário de variáveis para que leitor entenda.

In [ ]:
#Todas as colunas trazem a identificação das emendas, tais quais os planos orçamentários, ações e valores.

## 4) Existem valores nulos? quantos?

In [7]:
nulos = data.isnull().sum()
print(nulos)

Código da Emenda                      0
Ano da Emenda                         0
Tipo de Emenda                        0
Código do Autor da Emenda             0
Nome do Autor da Emenda               0
Número da emenda                      0
Localidade de aplicação do recurso    0
Código Município IBGE                 0
Município                             0
Código UF IBGE                        1
UF                                    1
Região                                1
Código Função                         1
Nome Função                           1
Código Subfunção                      1
Nome Subfunção                        1
Código Programa                       1
Nome Programa                         1
Código Ação                           1
Nome Ação                             1
Código Plano Orçamentário             1
Nome Plano Orçamentário               1
Valor Empenhado                       1
Valor Liquidado                       1
Valor Pago                            1
Valor Restos A Pagar Inscritos        1
Valor Restos A Pagar Cancelados       1
Valor Restos A Pagar Pagos            1
dtype: int64

## 5) Mostre os tipos das variáveis (se int, string, boolean, float...) e analise se alguma variável parece ter o tipo errado. Faça isso da maneira mais objetiva e otimizada possível.

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6606 entries, 0 to 6605
Data columns (total 28 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Código da Emenda                    6606 non-null   object
 1   Ano da Emenda                       6606 non-null   int64
 2   Tipo de Emenda                      6606 non-null   object
 3   Código do Autor da Emenda           6606 non-null   object
 4   Nome do Autor da Emenda             6606 non-null   object
 5   Número da emenda                    6606 non-null   object
 6   Localidade de aplicação do recurso  6606 non-null   object
 7   Código Município IBGE               6606 non-null   object
 8   Município                           6606 non-null   object
 9   Código UF IBGE                      6605 non-null   float64
 10  UF                                  6605 non-null   object
 11  Região                              6605 non-null   object
 12  Código Função                       6605 non-null   float64
 13  Nome Função                         6605 non-null   object
 14  Código Subfunção                    6605 non-null   float64
 15  Nome Subfunção                      6605 non-null   object
 16  Código Programa                     6605 non-null   float64
 17  Nome Programa                       6605 non-null   object
 18  Código Ação                         6605 non-null   object
 19  Nome Ação                           6605 non-null   object
 20  Código Plano Orçamentário           6605 non-null   float64
 21  Nome Plano Orçamentário             6605 non-null   object
 22  Valor Empenhado                     6605 non-null   object
 23  Valor Liquidado                     6605 non-null   object
 24  Valor Pago                          6605 non-null   object
 25  Valor Restos A Pagar Inscritos      6605 non-null   object
 26  Valor Restos A Pagar Cancelados     6605 non-null   object
 27  Valor Restos A Pagar Pagos          6605 non-null   object
dtypes: float64(5), int64(1), object(22)
memory usage: 1.4+ MB

Se alguma coluna estiver com o tipo errado, escreva abaixo qual é e por que isso pode atrapalhar análises.

**Dica:** Se alguma variável tiver no tipo o nome "object", isso se refere a texto.

In [ ]:
# diversas colunas, como as da 22-27 que são valores, estão constando como "object", sendo que deveriam constar como "int", que são números (valores inteiros). Isso atrapalha análises pois o valor entra como string, ou seja, concatena textos.

## 6) Usando a coluna `Ano da Emenda` como base, descubra até que ano o dataset está atualizado (mostre as 8 primeiras linhas do df ordenado desc).

In [9]:
data_sorted = data.sort_values(by='Ano da Emenda', ascending=False)
data_sorted.head(8)

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
6605,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,PARNARAMA - MA,2107803,PARNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,ALVORADA - RS,4300604,ALVORADA,4300000.0,...,1D73,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,0.0,APOIO A POLITICA NACIONAL DE DESENVOLVIMENTO U...,"700000,00","0,00","0,00","0,00","690900,00","9100,00"
1,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SANTA ISABEL DO PARÁ - PA,1506500,SANTA ISABEL DO PARÁ,1500000.0,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0.0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"487500,00","0,00","0,00","0,00","487500,00","0,00"
2,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,BARRA BONITA - SC,4202099,BARRA BONITA,4200000.0,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0.0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"100000,00","0,00","0,00","0,00","0,00","100000,00"
3,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,ARARAQUARA - SP,3503208,ARARAQUARA,3500000.0,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0.0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"243750,00","0,00","0,00","0,00","243750,00","0,00"
4,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CAMPO LARGO - PR,4104204,CAMPO LARGO,4100000.0,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0.0,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"1658333,94","0,00","0,00","0,00","527200,00","1131133,94"
5,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,CAMPINAS DO SUL - RS,4303806,CAMPINAS DO SUL,4300000.0,...,10V0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA,0.0,APOIO A PROJETOS DE INFRAESTRUTURA TURISTICA -...,"243750,00","0,00","0,00","0,00","0,00","243750,00"
6,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,MORENO - PE,2609402,MORENO,2600000.0,...,20RP,APOIO A INFRAESTRUTURA PARA A EDUCACAO BASICA,0.0,INFRAESTRUTURA PARA A EDUCACAO BASICA - DESPES...,"700000,00","0,00","0,00","0,00","700000,00","0,00"

Explique: qual é o ano mais recente presente no dataset?

In [ ]:
#o ano mais recente presente no dataset é 2014

## 7) execute um  `describe()` e explique uma conclusão simples que você consegue tirar a partir das estatísticas (se algumas colunas deveriam aparecer no describe mas não aparecem, indique o motivo que você acredita que esteja causando esse problema).

In [10]:
data.describe()

,Ano da Emenda,Código UF IBGE,Código Função,Código Subfunção,Código Programa,Código Plano Orçamentário
count,6606.0,6.605000e+03,6605.000000,6605.000000,6605.000000,6605.0
mean,2014.0,3.269417e+06,14.314156,420.774716,2031.032854,0.0
std,0.0,1.030702e+06,5.585321,193.749878,20.105837,0.0
min,2014.0,-1.000000e+00,4.000000,122.000000,2012.000000,0.0
25%,2014.0,2.600000e+06,10.000000,301.000000,2015.000000,0.0
50%,2014.0,3.200000e+06,12.000000,302.000000,2015.000000,0.0
75%,2014.0,4.100000e+06,20.000000,542.000000,2054.000000,0.0
max,2014.0,5.300000e+06,27.000000,847.000000,2108.000000,0.0

In [ ]:
#acredito que algumas linhas estão com o tipo de variável (string, int, float) errados, devido à isso, as colunas deveriam aparecer e por isso não aparecem

## 8) Mostre as últimas 5 linhas do dataset e escreva se a última linha parece completa (sem muitos nulos) ou não.

In [11]:
data.tail(5)

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
6601,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,MIRA ESTRELA - SP,3530003,MIRA ESTRELA,3500000.0,...,14U2,"IMPLANTACAO, INSTALACAO E AMPLIACAO DE ESPACOS...",0.0,"IMPLANTACAO, INSTALACAO E MODERNIZACAO DE ESPA...","343000,00","0,00","0,00","0,00","0,00","343000,00"
6602,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,DIVINÓPOLIS DE GOIÁS - GO,5208301,DIVINÓPOLIS DE GOIÁS,5200000.0,...,0E53,AQUISICAO DE VEICULOS PARA O TRANSPORTE ESCOLA...,0.0,APOIO AO TRANSPORTE ESCOLAR PARA A EDUCACAO BA...,"150000,00","0,00","0,00","0,00","0,00","150000,00"
6603,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SEROPÉDICA - RJ,3305554,SEROPÉDICA,3300000.0,...,5450,IMPLANTACAO E MODERNIZACAO DE INFRAESTRUTURA P...,0.0,IMPLANTACAO E MODERNIZACAO DE INFRAESTRUTURA P...,"250000,00","0,00","0,00","0,00","243750,00","6250,00"
6604,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,JESUÍTAS - PR,4112751,JESUÍTAS,4100000.0,...,20ZV,FOMENTO AO SETOR AGROPECUARIO,0.0,FOMENTO AO SETOR AGROPECUARIO - DESPESAS DIVERSAS,"97500,00","97500,00","97500,00","0,00","0,00","0,00"
6605,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,PARNARAMA - MA,2107803,PARNA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Interprete a completude da última linha.

In [ ]:
# A última linha não possue nulos

## 9) existem valores duplicados no dataframe? Caso positivo, quantos?

In [12]:
dup = data.duplicated().sum()
print(dup)

0